MovieApp/Controllers/GraphsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MovieApp.Data;
using MovieApp.Models;

namespace MovieApp.Controllers
{
    public class GraphsController : Controller
    {
        private readonly MovieAppContext _context;

        public GraphsController(MovieAppContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        // GET: Movies/Graphs/Screen/1
        public async Task<IActionResult> Screen(int? demantion)
        {
            if (demantion == 1)
            {
                return View("OneDemantionGraphs");
            } else if(demantion == 2)
            {
                return View("TwoDemantionGraphs");
            } else if(demantion == 3)
            {
                return View("ThreeDemantionGraphs");
            }

            return View();
        }

        // GET: Graphs/Count/:splice&:context
        public async Task<IActionResult> Count(string? splice, string? context)
        {
            if (splice != null)
            {
                if (context == "Officials")
                {
                    var list =
                        _context.Official
                        .ToList()
                       .GroupBy(m => m.GetType().GetProperty(splice).GetValue(m, null))
                       .Select(m => new
                       {
                           Key = m.Key.ToString(),
                           Count = m.Count()
                       })
                       .ToList();
                    return Json(list);
                }
                else if (context == "Movies")
                {
                    var list =
                        _context.Movie
                        .ToList()
                       .GroupBy(m => m.GetType().GetProperty(splice).GetValue(m, null))
                       .Select(m => new
                       {
                           Key = m.Key.ToString(),
                           Count = m.Count()
                       })
                       .ToList();
                    return Json(list);
                }
                else
                {
                    return null;
                }
            } else { 
                return null;
            }
        }

        // GET: Graphs/Average/:avgOf:avgBy:context
        public async Task<IActionResult> Average(string? avgOf, string? avgBy, string? context)
        {
            if (avgOf != null && avgBy != null)
            {
                if (context == "Officials")
                {
                    var list = _context.Official
                    .ToList()
                   .GroupBy(m => m.GetType().GetProperty(avgBy).GetValue(m, null))
                   .Select(m => new
                   {
                       Key = m.Key.ToString(),
                       Count = m.Average(r => Convert.ToDouble(DateTime.Now.Year - r.Birthdate.Year))
                   })
                   .ToList();
                    return Json(list);
                } 
                else if (context == "Movies")
                {
                    var list = _context.Movie
                    .ToList()
                   .GroupBy(m => m.GetType().GetProperty(avgBy).GetValue(m, null))
                   .Select(m => new
                   {
                       Key = m.Key.ToString(),
                       Count = m.Average(r => Convert.ToDouble(r.GetType().GetProperty(avgOf).GetValue(r, null).ToString()))
                   })
                   .ToList();
                    return Json(list);
                }
                else if (context == "Soundtracks")
                {
                    var list = _context.Movie
                        .Join(_context.SoundtrackOfMovie,
                            m => m.Id,
                            som => som.MovieId,
                            (m, som) => new
                            {
                                movieId = m.Id,
                                soundtrackId = som.SoundtrackId,
                                groupByAvg = som.Soundtrack.GetType().GetProperty(avgOf).GetValue(som.Soundtrack, null),
                                groupByKey = m.GetType().GetProperty(avgBy).GetValue(m, null)
                            })
                        .ToList()
                        .GroupBy(p => p.groupByKey)
                        .Select(gb => new
                        {
                            Key = gb.Key.ToString(),
                            Count = gb.Average(a => (double)a.groupByAvg)
                        })
                        .ToList();
                    return Json(list);
                }
                else
                {
                    return null;
                }
            }
            else
            {
                return null;
            }
        }

        // GET: Graphs/Groupby/
        public async Task<IActionResult> Groupby()
        {
            var list = _context.Movie
                .Join(_context.OfficialOfMovie,
                    m => m.Id,
                    oom => oom.MovieId,
                    (m, oom) => new
                    {
                        movieId = m.Id,
                        rating = m.Rating,
                        duration = m.Duration,
                        genre = m.Genre,
                        name = m.Name,
                        officialId = oom.OfficialId
                    })
                .GroupBy(p => new { p.duration, p.rating, p.genre, p.movieId, p.name})
                .Select(gb => new
                {
                    Duration = gb.Key.duration,
                    Rating = gb.Key.rating,
                    Genre = gb.Key.genre,
                    Name = gb.Key.name,
                    Count = gb.Count()
                })
                .ToList();
            return Json(list);
        }
    }
}

MovieApp/Views/Shared/Map.cshtml
@{
    ViewBag.Title = "Map";
}

<script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBAcpASlmqwBs5DpRzYzOo4-Tymi8lnp_o&callback=initMap&libraries=geometry&v=weekly"
        defer></script>
<style type="text/css">

        html,
        body {
            height: 100%;
            margin: 0;
            padding: 0;
        }
</style>
<script>
    "use strict";

    let map;
    var locationsToPlace = @Json.Serialize(ViewBag.locations);

    function initMap() {
        map = new google.maps.Map(document.getElementById("map"), {
            center: {
                lat: 31.771959,
                lng: 35.217018
            },
            zoom: 2
        });

        let geocoder = new google.maps.Geocoder();

        for (var locationId in locationsToPlace) {
            geocodeEncapsulation(locationId);
            
        }
   

    function geocodeEncapsulation(locationId) {
        geocoder.geocode({ 'address': locationsToPlace[locationId].country }, function(results, status) {

            var contentString = '<div style="display:flex; flex-direction:column;  padding: 10px;">' +
                '<div>' +
                '<div style="float:left">' +
                `<img src="${locationsToPlace[locationId].imageUrl}" width="50" height="50">` +
                '</div>' +
                '<div style="float: right;">' +
                `<h3>${locationsToPlace[locationId].name}</h3>` +
                `<h5>${locationsToPlace[locationId].country}</h5>` +
                '</div>' +
                '</div>' +
                `<div><a href="/Movies/Details/${locationId.substring(2)}">Click here</a> to learn more</div>` +
                '</div>';

            var infowindow = new google.maps.InfoWindow({ maxWidth: 1000 });

            if (status == google.maps.GeocoderStatus.OK) {

                var randomPlaceInCountry = google.maps.geometry.spherical.computeOffset(results[0].geometry.location,
                    Math.floor(Math.random() * 5000), Math.floor(Math.random() * 360));

                var marker = new google.maps.Marker({
                    position: randomPlaceInCountry,
                    map: map,
                    title: locationsToPlace[locationId].name
                });

                google.maps.event.addListener(marker, 'click', (function (marker, contentString, infowindow) {
                    return function () {
                        infowindow.setContent(contentString);
                        infowindow.open(map, marker);
                    };
                })(marker, contentString, infowindow));

            } else {
                if (status == google.maps.GeocoderStatus.OVER_QUERY_LIMIT) {
                    console.log("TIMEOUT: " + locationsToPlace[locationId].country);

                    setTimeout(function() {
                        geocodeEncapsulation(locationId);
                    }, 250);
                } else {
                     console.log("Could not find location: " + locationsToPlace[locationId].country);
                }   
            }
        });
        }
    }
</script>

<div id="map"></div>

MovieApp/Views/Shared/Navbar.cshtml
@{
    ViewData["Title"] = "Navbar";
}

<!-- Navigation -->
    <ul class="navbar-nav sidebarLink">
        <li class="nav-item">
            <a class="nav-link" asp-controller="Movies" asp-action="Index">
                <i class="fa fa-film"></i> מאגר הסרטים
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" asp-controller="Officials" asp-action="Index">
                <i class="fa fa-person-booth"></i> בעלי התפקידים
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" asp-controller="Soundtracks" asp-action="Index">
                <i class="fa fa-play-circle"></i> מאגר פסקולים
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" asp-controller="Movies" asp-action="CountriesMapped">
                <i class="fas fa-map-marked-alt"></i> סרטים במפה
            </a>
        </li>

        <li class="nav-item">
            <a class="nav-link" asp-controller="Movies" asp-action="Seen">
                <i class="fa fa-eye"></i> סרטים שראיתי
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" asp-controller="Movies" asp-action="Watchlist">
                <i class="fa fa-list"></i> רשימת צפייה
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" asp-controller="Graphs" asp-action="Index">
                <i class="fa fa-chart-pie"></i> גרפים
            </a>
        </li>

        @if (User.HasClaim(ClaimTypes.Role, Account.UserType.Admin.ToString()))
        {
        <li class="nav-item">
            <a class="nav-link" asp-controller="Account" asp-action="Index">
                <i class="fa fa-users-cog"></i> ניהול משתמשים
            </a>
        </li>
        }
    </ul>

MovieApp/Views/Shared/NavbarSearch.cshtml
@{
    ViewData["Title"] = "NavbarSearch";
}

  // TODO: if we want this feature, we need to develop it, of course
<!-- Search form -->
<!--<form class="navbar-search navbar-search-light form-inline mr-sm-3" id="navbar-search-main">
    <div class="form-group mb-0">
        <div class="input-group input-group-alternative input-group-merge">
            <div class="input-group-prepend">
                <span class="input-group-text">
                    <i class="fas fa-search"></i>
                </span>
            </div>
            <input class="form-control" placeholder="חפש..." type="text">
        </div>
    </div>
    <button type="button" class="close" data-action="search-close" data-target="#navbar-search-main" aria-label="Close">
        <span aria-hidden="true">×</span>
    </button>
</form>-->

MovieApp/Views/Shared/UserMenu.cshtml
<div class="dropdown-menu dropdown-menu-left">
    <div class="dropdown-header noti-title">
        <h6 class="text-overflow m-0">ברוך הבא</h6>
    </div>
    @if (User.Identity.IsAuthenticated)
    {
        <a href="/Movies/Seen"" class="dropdown-item">
            <i class="ni ni-single-02"></i>
            <span>סרטים שראיתי</span>
        </a>
        <a href="/Movies/Watchlist" class="dropdown-item">
            <i class="ni ni-settings-gear-65"></i>
            <span>רשימת צפייה</span>
        </a>
        <div class="dropdown-divider">

        </div>
        <form class="form-inline" asp-controller="Account" asp-action="Logout">
            <button type="submit" class="dropdown-item logout">
                <i class="ni ni-user-run"></i>
                <span class="logout">התנתק</span>
            </button>
        </form>
    }
    else
    {
        <a class="dropdown-item" asp-controller="Account" asp-action="Login">
            <i class="ni ni-single-02"></i>
            <span>התחברות</span>
        </a>
        <a class="dropdown-item" asp-controller="Account" asp-action="Register">
            <i class="ni ni-single-02"></i>
            <span>הרשמה</span>
        </a>}
</div>

MovieApp/Views/Shared/_Layout.cshtml
    
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Action!</title>

    <!-- Favicon -->
    <link href="~/img/logo.png" rel="icon" type="image/png">

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
    <!-- Icons -->
    <link href="~/vendor/nucleo/css/nucleo.css" rel="stylesheet" asp-append-version="true">
    <link href="~/vendor/@@fortawesome/fontawesome-free/css/all.min.css" rel="stylesheet" asp-append-version="true">
    <!-- Argon CSS -->
    <link type="text/css" href="~/css/argon.css?v=1.2.0" rel="stylesheet" asp-append-version="true">
    <!-- App CSS -->
    <link type="text/css" href="~/css/site.css" rel="stylesheet" asp-append-version="true">

    <!-- Social tags -->
    <meta name="keywords" content="creative tim, udevoffice, html dashboard, html css dashboard, web dashboard, bootstrap 4 dashboard, node dashboard, node.js dashboard, bootstrap 4, node.js, node, css3 dashboard, bootstrap 4 admin, argon node dashboard, argon node.js dashboard, bootstrap 4 dashboard, frontend, responsive bootstrap 4 dashboard, argon node design, argon node.js design, argon node dashboard, argon node.js dashboard, bootstrap">
    <meta name="description" content="Start your development with a Bootstrap 4 Admin Dashboard built for Asp.net framework, the newest go-to technology for top companies.It features a huge number of components that can help you create amazing websites and brings with itself innumerable advantages: lightweight, fast, scalable and modern way to execute your next top app.">

    <!-- Schema.org markup for Google+ -->
    <meta itemprop="name" content="Argon Dashboard Asp.net by Creative Tim">
    <meta itemprop="description" content="Start your development with a Bootstrap 4 Admin Dashboard built for Asp.net framework, the newest go-to technology for top companies.It features a huge number of components that can help you create amazing websites and brings with itself innumerable advantages: lightweight, fast, scalable and modern way to execute your next top app.">

    <meta itemprop="image" content="https://s3.amazonaws.com/creativetim_bucket/products/162/opt_ad_asp_thumbnail.jpg">

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="product">
    <meta name="twitter:site" content="@@creativetim">
    <meta name="twitter:title" content="Argon Dashboard Asp.net by Creative Tim">

    <meta name="twitter:description" content="Start your development with a Bootstrap 4 Admin Dashboard built for Asp.net framework, the newest go-to technology for top companies.It features a huge number of components that can help you create amazing websites and brings with itself innumerable advantages: lightweight, fast, scalable and modern way to execute your next top app.">
    <meta name="twitter:creator" content="@@creativetim">
    <meta name="twitter:image" content="https://s3.amazonaws.com/creativetim_bucket/products/162/opt_ad_asp_thumbnail.jpg">


    <!-- CSS files -->
    <link rel="stylesheet" href="~/css/style.css" asp-append-version="true">

    @RenderSection("Styles", required: false)
    @RenderSection("HeadScripts", required: false)
</head>
<body>
    @{bool isUserConnected = User.Identity.IsAuthenticated; }
    @{ string imgProfile = @Context.User.Claims.FirstOrDefault(c => c.Type == System.Security.Claims.ClaimTypes.Uri)?.Value;}
    @{ string username = @Context.User.Claims.FirstOrDefault(c => c.Type == System.Security.Claims.ClaimTypes.Name)?.Value;}
    <!---------------- SIDEBAR ---------------->

    @if (isUserConnected)
    {
        <nav class="navbar navbar-vertical fixed-right navbar-expand-md navbar-dark bg-dark sidebar" id="sidenav-main">
            <div class="container-fluid">

                <!-- Toggler -->
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <!-- Brand -->
                <div class="brand-holder">
                    <a class="navbar-brand pt-0" href="/">
                        @*TODO: ADD SVG LOGO*@
                        MovieApp
                    </a>
                </div>

                <!-- User -->
                <ul class="nav align-items-center d-md-none">
                    <li class="nav-item dropdown">
                        <a class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <div class="media align-items-center">
                                @if (isUserConnected)
                                {
                                    <span class="avatar avatar-sm rounded-circle">
                                        @if (imgProfile != null)
                                        {
                                            <img alt="Profile img" src=@("/img/accounts/" + imgProfile)>
                                        }
                                        else
                                        {
                                            <img alt="Profile img" src=@("/img/accounts/default.png")>
                                        }
                                    </span>
                                }
                            </div>
                        </a>

                        <partial name="UserMenu" />
                    </li>
                </ul>

                <!-- Collapse -->
                <div class="collapse navbar-collapse" id="sidenav-collapse-main">
                    <!-- Collapse header -->
                    <div class="navbar-collapse-header d-md-none">
                        <div class="row">
                            <div class="col-6 collapse-brand">
                                <a href="/">
                                    MovieApp
                                </a>
                            </div>
                            <div class="col-6 collapse-close" style="text-align: left;">
                                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle sidenav">
                                    <span></span>
                                    <span></span>
                                </button>
                            </div>
                        </div>
                    </div>

                    <!-- Navigation -->
                    <partial name="Navbar" />


                </div>
            </div>
        </nav>
    }

    <!---------------- MAIN ---------------->
    <div class="main-content">
        <!-- TopNav -->
        <nav class="navbar navbar-top navbar-expand navbar-dark bg-danger border-bottom">
            <div class="container-fluid">
                <div class="collapse navbar-collapse" id="navbarSupportedContent">

                    <!-- Navbar links -->
                    <!-- Current user (right part of the website) -->
                    <ul class="navbar-nav align-items-center mr-auto ">
                        <li class="nav-item dropdown">
                            <a class="nav-link pr-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <div class="media align-items-center">
                                    @if (isUserConnected)
                                    {
                                        <span class="avatar avatar-sm rounded-circle">

                                            @if (imgProfile != null)
                                            {
                                                <img alt="Profile img" src=@("/img/accounts/" + imgProfile)>
                                            }
                                            else
                                            {
                                                <img alt="Profile img" src=@("/img/accounts/default.png")>
                                            }
                                        </span>
                                    }
                                    <div class="media-body  mr-2  d-none d-lg-block">
                                        <span class="mb-0 text-sm  font-weight-bold">
                                            @if (isUserConnected)
                                            {
                                                @username
                                            }
                                            else
                                            { <span>Guest</span>}
                                        </span>
                                    </div>
                                </div>
                            </a>

                            <partial name="UserMenu" />

                        </li>
                    </ul>
                </div>
            </div>
        </nav>

        @RenderSection("VideoSection", required: false)

        <!-- Page content -->
        <div class="container-fluid rendered-content">
            <!-- Page content -->
            @RenderBody()

        </div>


        <partial name="Footer" />


    </div>

    <!-- Argon Scripts -->
    <!-- Core -->
    <script src="~/vendor/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    <script src="~/vendor/bootstrap/dist/js/bootstrap.bundle.min.js" asp-append-version="true"></script>
    <script src="~/vendor/js-cookie/js.cookie.js" asp-append-version="true"></script>
    <script src="~/vendor/jquery.scrollbar/jquery.scrollbar.min.js" asp-append-version="true"></script>
    <script src="~/vendor/jquery-scroll-lock/dist/jquery-scrollLock.min.js" asp-append-version="true"></script>
    <!-- Docs JS -->
    <script src="~/vendor/anchor-js/anchor.min.js" asp-append-version="true"></script>
    <script src="~/vendor/clipboard/dist/clipboard.min.js" asp-append-version="true"></script>
    <script src="~/vendor/holderjs/holder.min.js" asp-append-version="true"></script>
    <script src="~/vendor/prismjs/prism.js" asp-append-version="true"></script>
    <!-- Optional JS -->
    <script src="~/vendor/chart.js/dist/Chart.min.js" asp-append-version="true"></script>
    <script src="~/vendor/chart.js/dist/Chart.extension.js" asp-append-version="true"></script>
    <script src="~/vendor/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js" asp-append-version="true"></script>
    <!-- Argon JS -->
    <script src="~/js/argon.js" asp-append-version="true"></script>

    <!--MovieApp JS -->
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>