MovieApp/Models/Official.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace MovieApp.Models
{
    public class Official
    {
        [Key]
        public int Id { get; set; }

        [Display(Name = "שם פרטי")]
        public string FirstName { get; set; }

        [Display(Name = "שם משפחה")]
        public string LastName { get; set; }

        [Display(Name = "תפקיד")]
        public OfficialRole Role { get; set; }

        [Display(Name = "מגדר")]
        public OfficialGender Gender { get; set; }

        [Display(Name = "תאריך לידה")]
        [DataType(DataType.Date)]
        public DateTime Birthdate { get; set; }

        [Display(Name = "מדינת מוצא")]
        public string OriginCountry { get; set; }

        [NotMapped]
        [Display(Name = "תמונה")]
        public IFormFile Image { get; set; }

        public string ImageUrl { get; set; }

        [Display(Name = "סרטים שבהם משתתף")]
        public ICollection<OfficialOfMovie> OfficialOfMovies { get; set; }

        [Display(Name = "שם מלא")]
        public virtual string FullName { get { return FirstName + " " + LastName; } }

        [Display(Name = "גיל")]
        public virtual int Age { get
            {
                DateTime now = DateTime.Today;
                int age = now.Year - Birthdate.Year;
                if (Birthdate > now.AddYears(-age)) age--;
                return age;
            } }

        public enum OfficialGender
        {
            זכר,
            נקבה,
            אחר
        }

        public enum OfficialRole
        {
            מפיק,
            במאי,
            תסריטאי,
            צלם,
            שחקן,
            עורך,
            סאונדמן,
            זמר,
            פזמונאי
        }

        public enum OfficialSpliceOptions
        {
            [Display(Name = "תפקיד")]
            Role,
            [Display(Name = "מגדר")]
            Gender,
            [Display(Name = "מדינת מוצא")]
            OriginCountry
        }

        public enum OfficialAverageOfOptions
        {
            [Display(Name = "גיל")]
            Age
        }

        public enum OfficialAverageByOptions
        {
            [Display(Name = "תפקיד")]
            Role,
            [Display(Name = "מדינת מוצא")]
            OriginCountry
        }
    }
}

MovieApp/Models/OfficialController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace MovieApp.Models
{
    public class OfficialController : Controller
    {
        // GET: OfficialController
        public ActionResult Index()
        {
            return View();
        }

        // GET: OfficialController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: OfficialController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: OfficialController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: OfficialController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: OfficialController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: OfficialController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: OfficialController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

MovieApp/Controllers/OfficialsController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MovieApp.Data;
using MovieApp.Models;
using MovieApp.Models.TMDB;
using X.PagedList;

namespace MovieApp.Controllers
{
    [Authorize]
    public class OfficialsController : Controller
    {
        private readonly MovieAppContext _context;
        private readonly IWebHostEnvironment _hostEnvironment;

        public OfficialsController(MovieAppContext context, IWebHostEnvironment hostEnvironment)
        {
            _context = context;
            this._hostEnvironment = hostEnvironment;
        }

        // GET: Officials
        public async Task<IActionResult> Index(string nameFilter, string currentNameFilter, int? page)
        {
            var officials = await _context.Official.ToListAsync();

            if (nameFilter != null)
            {
                page = 1;
            }
            else
            {
                nameFilter = currentNameFilter;
            }

            ViewBag.CurrentNameFilter = nameFilter;

            if (!String.IsNullOrEmpty(nameFilter))
            {
                officials = officials.Where(o => o.FirstName.ToLower().Contains(nameFilter.ToLower()) || o.LastName.ToLower().Contains(nameFilter.ToLower())).ToList();
            }

            int pageSize = 8;
            int pageNumber = page ?? 1;

            return View(officials.ToPagedList(pageNumber, pageSize));
        }

        // GET: Officials/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var official = await _context.Official.Include(o => o.OfficialOfMovies).ThenInclude(oof => oof.Movie)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (official == null)
            {
                return NotFound();
            }

            return View(official);
        }

        // GET: Officials/Create
        public IActionResult Create()
        {
            var countries = new SelectList(CultureHelper.CountryList(), "Key", "Value");
            ViewBag.MovieId = new SelectList(_context.Movie, "Id", "Id");
            ViewBag.MovieName = new SelectList(_context.Movie, "Id", "Name");
            ViewBag.Countries = countries.OrderBy(p => p.Text).ToList();

            return View();
        }

        // POST: Officials/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FirstName,LastName,Role,Gender,Birthdate,OriginCountry,Image,ImageUrl")] Official official, int[] MovieId)
        {
            if (ModelState.IsValid)
            {
                if (official.Image != null)
                {
                    string fileName = Path.GetFileNameWithoutExtension(official.Image.FileName);
                    string extension = Path.GetExtension(official.Image.FileName);
                    official.ImageUrl = fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                    string path = Path.Combine(_hostEnvironment.WebRootPath + "/img/officials/", fileName);

                    using (var fileStream = new FileStream(path, FileMode.Create))
                    {
                        await official.Image.CopyToAsync(fileStream);
                    }
                }
                else
                {
                    official.ImageUrl = "default-preson.jpg";
                }

                official.OriginCountry = CultureHelper.GetCountryByIdentifier(official.OriginCountry);
                official.OfficialOfMovies = new List<OfficialOfMovie>();
                foreach (var id in MovieId)
                {
                    official.OfficialOfMovies.Add(new OfficialOfMovie() { MovieId = id, OfficialId = official.Id });
                }

                _context.Add(official);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(official);
        }

        // GET: Officials/Edit/5

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var official = await _context.Official
                .Include(o => o.OfficialOfMovies)
                .FirstOrDefaultAsync(o => o.Id == id);
            if (official == null)
            {
                return NotFound();
            }



            IEnumerable<SelectListItem> countriesSelectList = from c in CultureHelper.CountryList()
                                                              select new SelectListItem
                                                              {
                                                                  Value = c.Key,
                                                                  Text = c.Value,
                                                                  Selected = CultureHelper.GetCountryByIdentifier(c.Key) == official.OriginCountry
                                                              };
            ViewBag.Countries = countriesSelectList.OrderBy(p => p.Text).ToList();

            List<SelectListItem> movieNameSelectList = new List<SelectListItem>();
            foreach (var m in _context.Movie)
            {
                SelectListItem s = new SelectListItem();
                s.Value = m.Id.ToString();
                s.Text = m.Name;
                s.Selected = official.OfficialOfMovies.Any(oom => m.Id == oom.MovieId);
                movieNameSelectList.Add(s);
            }
            ViewBag.MovieName = movieNameSelectList;

            return View(official);
        }

        // POST: Officials/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FirstName,LastName,Role,Gender,Birthdate,OriginCountry,Image,ImageUrl")] Official official, int[] MovieId)
        {
            if (id != official.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var original_data = _context.Official.AsNoTracking().Where(d => d.Id == id).FirstOrDefault();
                    if (official.Image != null)
                    {
                        if (original_data.ImageUrl != null)
                        {
                            var imagePath = Path.Combine(_hostEnvironment.WebRootPath, "img/officials", original_data.ImageUrl);
                            if (System.IO.File.Exists(imagePath))
                            {
                                System.IO.File.Delete(imagePath);
                            }
                        }

                        string fileName = Path.GetFileNameWithoutExtension(official.Image.FileName);
                        string extension = Path.GetExtension(official.Image.FileName);
                        official.ImageUrl = fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                        string path = Path.Combine(_hostEnvironment.WebRootPath + "/img/officials/", fileName);

                        using (var fileStream = new FileStream(path, FileMode.Create))
                        {
                            await official.Image.CopyToAsync(fileStream);
                        }
                    }
                    else
                    {
                        official.ImageUrl = original_data.ImageUrl;
                    }

                    official.OriginCountry = CultureHelper.GetCountryByIdentifier(official.OriginCountry);
                    if (official.OfficialOfMovies == null)
                    {
                        official.OfficialOfMovies = new List<OfficialOfMovie>();
                    }

                    foreach (var movieId in MovieId)
                    {
                        official.OfficialOfMovies.Add(new OfficialOfMovie() { MovieId = movieId, OfficialId = official.Id });
                    }

                    _context.OfficialOfMovie.RemoveRange(_context.OfficialOfMovie.Where(oom => oom.OfficialId == official.Id));
                    _context.OfficialOfMovie.AddRange(official.OfficialOfMovies);

                    _context.Update(official);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OfficialExists(official.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(official);
        }

        // GET: Officials/Delete/5
        [Authorize(Roles = "Admin")]

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var official = await _context.Official
                .FirstOrDefaultAsync(m => m.Id == id);
            if (official == null)
            {
                return NotFound();
            }

            return View(official);

MovieApp/Views/Officials/Create.cshtml
@model MovieApp.Models.Official

@{
    ViewData["Title"] = "יצירה";
}

<div class="row">
    <div class="col-xl-8 order-xl-1">
        <div class="card bg-secondary shadow">
            <div class="card-header bg-white border-0">
                <div class="row align-items-center">
                    <div class="col-8">
                        <h3 class="mb-0">יצירת בעל תפקיד</h3>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <form asp-action="Create" enctype="multipart/form-data">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="FirstName" class="control-label"></label>
                                <input asp-for="FirstName" class="form-control" />
                                <span asp-validation-for="FirstName" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="LastName" class="control-label"></label>
                                <input asp-for="LastName" class="form-control" />
                                <span asp-validation-for="LastName" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="Role" class="control-label"></label>
                                <select asp-for="Role" asp-items="Html.GetEnumSelectList<Official.OfficialRole>()" class="form-control">
                                    <option></option>
                                </select>
                                <span asp-validation-for="Role" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="Gender" class="control-label"></label>
                                <select asp-for="Gender" asp-items="Html.GetEnumSelectList<Official.OfficialGender>()" class="form-control">
                                    <option></option>
                                </select>
                                <span asp-validation-for="Gender" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="Birthdate" class="control-label"></label>
                                <input asp-for="Birthdate" class="form-control" />
                                <span asp-validation-for="Birthdate" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="OriginCountry" class="control-label"></label>
                                <select asp-for="OriginCountry" asp-items="@(new SelectList(ViewBag.Countries, "Value", "Text"))" class="form-control">
                                    <option></option>
                                </select>
                                <span asp-validation-for="OriginCountry" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="OfficialOfMovies" class="control-label"></label>
                                <select name="MovieId" class="form-control" asp-items="ViewBag.MovieName" multiple></select>
                            </div>
                        </div>

                        <div class="post-image empty">
                            <div class="upload-section">
                                <input asp-for="Image" class="form-control upload-img" accept="image/*" />
                                <label class="icon-camera" for="Image">

                                    <img src=@("/img/icons/cameraPlus.png") />
                                </label>
                                <p>תמונה</p>
                            </div>
                            <div class="preview-section"></div>

                        </div>

                        <div class="col-md-6">
                            <div class="form-group">
                                <input type="submit" value="יצירה" class="btn btn-primary" />
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<div>
    <a asp-action="Index">בחזרה לרשימה</a>
</div>

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }

MovieApp/Views/Officials/Details.cshtml
@model MovieApp.Models.Official

@{
    ViewData["Title"] = "פרטי תפקיד";
}


<div class="row" style="margin-bottom: 50px">
    <div class="col-xl-8 order-xl-1">
        <div class="card bg-secondary shadow ">
            <div class="card-header">
                <h3 class="mb-0"> @Html.DisplayFor(model => model.FirstName)</h3>
            </div>
            <div class="card-body">
                <dl class="row">
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.LastName)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.LastName)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Role)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Role)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Gender)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Gender)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Birthdate)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Birthdate)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.OriginCountry)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.OriginCountry)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Image)
                    </dt>
                    <dd class="col-sm-10">
                        <img src="@("/img/officials/"+ Model.ImageUrl)" width="200" height="200">
                    </dd>
                    <dt class="col-sm-3">
                        @Html.DisplayNameFor(model => model.OfficialOfMovies)
                    </dt>
                    <dd class="col-sm-10">
                        <table class="table table-bordered table-condensed table-striped table-hover">
                            <thead>
                                <tr>
                                    <th>
                                        @Html.DisplayNameFor(model => model.OfficialOfMovies.First().Movie.Name)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.OfficialOfMovies.First().Movie.Genre)
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.OfficialOfMovies)
                                {
                                    <tr onclick="window.location='/Movies/Details/@item.MovieId'" style="cursor:pointer">
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Movie.Name)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Movie.Genre)
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </dd>
                </dl>
            </div>
            <div class="card-footer">
                <a asp-action="Index" class="btn btn-primary"><i class="fa fa-arrow-right"></i> בחזרה לרשימה</a>
                <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary"><i class="fa fa-edit"></i> ערוך</a>

                @if (User.HasClaim(ClaimTypes.Role, Account.UserType.Admin.ToString()))
                {
                    <form asp-action="Delete" style="display: inline-block;">
                        <input type="hidden" asp-for="Id" />
                        <input type="submit" value="מחק" class="btn btn-primary" />
                    </form>
                }
            </div>
        </div>
    </div>
</div>

MovieApp/Views/Officials/Index.cshtml
@using X.PagedList.Mvc.Core;
@model X.PagedList.IPagedList<MovieApp.Models.Official>

@{ ViewData["Title"] = "מאגר בעלי התפקידים"; }
<!-- CSS -->
<link type="text/css" href="~/css/officialsIndex.css?v=1.2.0" rel="stylesheet" asp-append-version="true">

<div class="jumbotron">
    <h1 class="display-4" dir="rtl">
        מאגר בעלי התפקידים
        <a class="btn btn-outline-light float-left" asp-action="Create"><i class="fas fa-plus"></i></a>
        <a class="btn btn-outline-light float-left" data-toggle="modal" data-target="#filters">
            <i class="fas fa-filter"></i>
        </a>

        <!-- Modal -->
        <div class="modal fade" id="filters" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="btn btn-sm" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form asp-controller="Officials" asp-action="Index" method="get">
                            <div class="form-group row">
                                <p class="col-sm-3">שם:</p>
                                <div class="col">
                                    <input type="text" name="nameFilter" class="form-control form-control-sm" value="@(ViewBag.CurrentNameFilter as string)" />
                                </div>
                            </div>
                            
                            <input type="submit" value="חפש" class="btn btn-danger" />
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </h1>

    <hr class="my-4">

    <div class="container">
        <div class="row row-cols-md-4 row-cols-sm-1 row-cols-xs-1">
            @foreach (var item in Model) 
            {
                <div class="col mb-4">
                 <div id="card-official" class="card h-100">
                     <img class="embed-responsive .embed-responsive-16by9 rounded-top" src="@("/img/officials/"+ item.ImageUrl)" alt="official">
                     <div class="card-img-overlay hoverOverlay bg-dark text-white rounded">
                        <h2 class="card-title">
                            <a asp-action="Details" asp-route-id="@item.Id" class="card-link">
                                @Html.DisplayFor(modelItem => item.FullName)
                            </a>
                        </h2>
                        <h3 class="card-subtitle text-muted">(@Html.DisplayFor(modelItem => item.Age))</h3>
                             
                        <div class="officialActions mx-auto">
                             <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-outline-light btn-sm fa fa-edit"></a>
                        </div>
                    </div>
                </div>
            </div>
            }
        </div>
    </div>

    <div class="pagination-container">
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page, currentNameFilter = ViewBag.CurrentNameFilter}))
    </div>
</div>