MovieApp/Controllers/MoviesController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MovieApp.Data;
using MovieApp.Models;
using MovieApp.Models.TMDB;
using MovieApp.Services;
using X.PagedList;

namespace MovieApp.Controllers
{
    [Authorize]

    public class MoviesController : Controller
    {
        private readonly MovieAppContext _context;
        private readonly IWebHostEnvironment _hostEnvironment;
        private TMDB TMDBService = new TMDB();
        private TwitterController twitter;

        public MoviesController(MovieAppContext context, IWebHostEnvironment hostEnvironment)
        {
            twitter = new TwitterController(context);
            _context = context;
            this._hostEnvironment = hostEnvironment;
        }

        // GET: Movies
        public async Task<IActionResult> Index(string nameFilter, string currentNameFilter, Movie.MovieGenre? genreFilter, Movie.MovieGenre? currentGenreFilter, string languageFilter, string currentLanguageFilter, int? page)
        {
            var userId = User.Claims.FirstOrDefault(c => c.Type == System.Security.Claims.ClaimTypes.Email)?.Value;

            Account account = await _context.Account.FirstOrDefaultAsync(m => m.Email == userId);
            ViewData["account"] = account;

            if (nameFilter != null || genreFilter != null || languageFilter != null)
            {
                page = 1;
            }
            else
            {
                nameFilter = currentNameFilter;
                genreFilter = currentGenreFilter;
                languageFilter = currentLanguageFilter;
            }

            ViewBag.CurrentNameFilter = nameFilter;
            ViewBag.CurrentLanguageFilter = languageFilter;

            var languages = new SelectList(CultureHelper.LanguageList(), "Key", "Value");
            ViewBag.Languages = languages.OrderBy(p => p.Text).ToList();

            var movies = await _context.Movie.ToListAsync();
            if (!String.IsNullOrEmpty(nameFilter))
            {
                movies = movies.Where(m => m.Name.ToLower().Contains(nameFilter.ToLower())).ToList();
            }
            if (genreFilter != null)
            {
                ViewBag.CurrentGenreFilter = (int)genreFilter;
                movies = movies.Where(m => m.Genre == genreFilter).ToList();
            }
            if (languageFilter != null)
            {
                movies = movies.Where(m => m.Language == CultureHelper.GetLanguageByIdentifier(languageFilter)).ToList();
            }

            int pageSize = 8;
            int pageNumber = page ?? 1;

            return View(movies.ToPagedList(pageNumber, pageSize));
        }

        // GET: Movies/Seen
        public async Task<IActionResult> Seen()
        {
            var userId = User.Claims.FirstOrDefault(c => c.Type == System.Security.Claims.ClaimTypes.Email)?.Value;

            Account account = await _context.Account.Include(m => m.MovieWatched).FirstOrDefaultAsync(m => m.Email == userId);
            ViewData["account"] = account;
            return View();
        }

        // GET: Movies/Watchlist
        public async Task<IActionResult> Watchlist()
        {
            var userId = User.Claims.FirstOrDefault(c => c.Type == System.Security.Claims.ClaimTypes.Email)?.Value;

            Account account = await _context.Account.Include(m => m.MovieWatchlist).FirstOrDefaultAsync(m => m.Email == userId);
            ViewData["account"] = account;
            return View();
        }

        // GET: Movies/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movie
                .Include(m => m.OfficialOfMovies).ThenInclude(oom => oom.Official)
                .Include(m => m.SoundtracksOfMovie).ThenInclude(som => som.Soundtrack).ThenInclude(s => s.Performer)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (movie == null)
            {
                return NotFound();
            }


            if (!User.Identity.IsAuthenticated) return BadRequest("User not logged in");

            var userId = User.Claims.FirstOrDefault(c => c.Type == System.Security.Claims.ClaimTypes.Email)?.Value;
            if (userId == null) return BadRequest("User email claim is empty");


            var account = await _context.Account.Include(x => x.MovieClicked).FirstOrDefaultAsync(m => m.Email == userId);
            if (account == null) return BadRequest("User not found");

            if (account.MovieClicked.Count == 5)
            {
                var moviesList = account.MovieClicked.ToList();
                moviesList.RemoveAt(0);
                account.MovieClicked = moviesList;
            }

            account.MovieClicked.Add(movie);


            await _context.SaveChangesAsync();


            return View(movie);
        }

        // GET: Movies/Create
        public IActionResult Create()
        {
            var countries = new SelectList(CultureHelper.CountryList(), "Key", "Value");
            ViewBag.Countries = countries.OrderBy(p => p.Text).ToList();

            var languages = new SelectList(CultureHelper.LanguageList(), "Key", "Value");
            ViewBag.Languages = languages.OrderBy(p => p.Text).ToList();

            ViewBag.OfficialId = new SelectList(_context.Official, "Id", "Id");
            IEnumerable<SelectListItem> officialNameSelectList = from o in _context.Official
                                                                 select new SelectListItem
                                                                 {
                                                                     Value = o.Id.ToString(),
                                                                     Text = o.FirstName + " " + o.LastName
                                                                 };
            ViewBag.OfficialName = officialNameSelectList;

            ViewBag.SoundtrackId = new SelectList(_context.Soundtrack, "Id", "Id");
            ViewBag.SoundtrackName = new SelectList(_context.Soundtrack, "Id", "Name");

            return View();
        }

        // POST: Movies/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Country,Language,Year,Genre,Duration,TrailerUrl,Rating,Image,ImageUrl,MovieIdInTMDB")] Movie movie, int[] OfficialsIds, int[] SoundtracksIds)
        {
            if (ModelState.IsValid)
            {
                movie.ImageUrl = (movie.ImageUrl == null) ? "/img/movies/defaultMoviePoster.png" : ("http://image.tmdb.org/t/p/w188_and_h282_bestv2" + movie.ImageUrl);
                movie.Country = CultureHelper.GetCountryByIdentifier(movie.Country);
                movie.Language = CultureHelper.GetLanguageByIdentifier(movie.Language);

                movie.OfficialOfMovies = new List<OfficialOfMovie>();
                foreach (var id in OfficialsIds)
                {
                    movie.OfficialOfMovies.Add(new OfficialOfMovie() { MovieId = movie.Id, OfficialId = id });
                }

                movie.SoundtracksOfMovie = new List<SoundtrackOfMovie>();
                foreach (var id in SoundtracksIds)
                {
                    movie.SoundtracksOfMovie.Add(new SoundtrackOfMovie() { MovieId = movie.Id, SoundtrackId = id });
                }

                _context.Add(movie);
                await _context.SaveChangesAsync();

                var userId = User.Claims.FirstOrDefault(c => c.Type == System.Security.Claims.ClaimTypes.Email)?.Value;

                if (userId == null)
                {
                    return BadRequest("User email claim is empty");
                }

                try
                {
                    var message = "HOT ALRET: new movie was added: " + movie.Name + " , Don't missed it!!";
                    string imagePath;
                    if (!movie.ImageUrl.StartsWith("http://") && !movie.ImageUrl.StartsWith("https://"))
                    {
                        imagePath = Path.Combine(_hostEnvironment.WebRootPath, movie.ImageUrl);
                    }
                    else
                    {
                        imagePath = movie.ImageUrl;

                    }

                    await twitter.PublishTweetAsync(userId, movie.Id, message, imagePath, Tweet.TweetType.MovieAdded);
                }
                catch (WebException)
                { }


                return RedirectToAction(nameof(Index));
            }
            return View(movie);
        }


        // GET: Movies/FindMovieId
        public async Task<List<MovieSearchResult>> FindMovieId(string name)
        {
            List<MovieSearchResult> movieResult = TMDBService.GetMovieIdByName(name);
            return movieResult;
        }

        // GET: Movies/FindMovieReviews
        public async Task<List<MovieReviewsResult>> FindMovieReviews(string id)
        {
            List<MovieReviewsResult> movieResult = TMDBService.GetMovieReviewsById(id);
            return movieResult;
        }


        // GET: Movies/FindMovieVideos
        public async Task<string> FindMovieVideos(string id)
        {
            string movieResult = TMDBService.GetMovieTrailerById(id);
            return movieResult;
        }

MovieApp/ViewComponents/RecommendMovieViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Security.Claims;
using Microsoft.AspNetCore.Mvc;
using MovieApp.Data;
using MovieApp.Models;
using Microsoft.EntityFrameworkCore;

namespace MovieApp.ViewComponents
{
    public class RecommendMovieViewComponent : ViewComponent
    {
        private MovieAppContext _context;
        List<Movie> _moviesRecommend;

        public RecommendMovieViewComponent(MovieAppContext context)
        {
            _context = context;
            _moviesRecommend = new List<Movie>();
        }

        private void GetRecommendList(IEnumerable<Movie.MovieGenre> listGenre, IEnumerable<Movie> alreadyWatched)
        {
            if (_moviesRecommend.Count < 3)
            {
                foreach (var genre in listGenre)
                {
                    var moviesByGenre = _context.Movie.Where(x => x.Genre == genre).OrderByDescending(x => x.Rating).ToList();
                    var filter = alreadyWatched.AsQueryable().Concat(_moviesRecommend);
                    var moviesFilter = moviesByGenre.Except(filter);
                    _moviesRecommend.AddRange(moviesFilter);
                }
            }
        }

        public async Task<IViewComponentResult> InvokeAsync(string path = "Index")
        {
            if (!User.Identity.IsAuthenticated) ViewData["message"] = "The user not logged in";

            string userId = ((ClaimsIdentity)User.Identity).FindFirst(ClaimTypes.Email)?.Value;
            if (userId == null) ViewData["message"] = "User email claim is empty";

            Account account = await _context.Account.Include(a => a.MovieWatched).Include(a => a.MovieClicked).Include(a => a.MovieWatchlist).FirstOrDefaultAsync(a => a.Email == userId);
            if (account == null) ViewData["message"] = "The user not found";

            var both = account.MovieWatched.ToList();
            both.AddRange(account.MovieClicked.ToList());
            var bothGenre = both.Select(x => x.Genre)
                .GroupBy(x => x)
                .Select(x => new { Genre = x.Key, Count = x.Count() })
                .OrderByDescending(x => x.Count)
                .Select(x => x.Genre);

            List<Movie> moviesReccomend; 
            if (account.MovieWatched.Count == 0 && account.MovieClicked.Count == 0) {
                moviesReccomend = _context.Movie.OrderByDescending(x => x.Rating).ToList();

            }
            else
            {

                GetRecommendList(bothGenre, account.MovieWatched);
                moviesReccomend = _moviesRecommend.Distinct().ToList();
            }

           
            ViewBag.moviesReccomend = (moviesReccomend.Count > 3) ? moviesReccomend.GetRange(0, 3) : moviesReccomend;
            ViewData["account"] = account;
            ViewBag.path = path;
            return View("_FindMoviesRecommend");
        }
    }
}

MovieApp/Views/Movies/CountriesMapped.cshtml
@model MovieApp.Models.Movie

@{
    ViewData["Title"] = "מפת הסרטים";
}

<h1 style="text-shadow: 2px 2px lightgray;">מפת הסרטים</h1>

<partial name="../Shared/Map.cshtml"/>

<style type="text/css">
    #map {
        height: 50vw;
    }
</style>

MovieApp/Views/Movies/Index.cshtml
@using X.PagedList.Mvc.Core;
@model X.PagedList.IPagedList<MovieApp.Models.Movie>

@{ ViewData["Title"] = "מאגר הסרטים"; }

@{ var account = ViewData["account"] as Account;}

<!-- CSS -->
<link type="text/css" href="~/css/moviesIndex.css?v=1.2.0" rel="stylesheet" asp-append-version="true">

<!-- Scripts -->
<script src="~/vendor/jquery/dist/jquery.min.js" asp-append-version="true"></script>

<script type='text/javascript'>
    var genreFilter = @Json.Serialize(ViewBag.CurrentGenreFilter);
    if (genreFilter != null) {
        $(function () {
            $('#genre-filter').val(genreFilter);
        });
    }
    var languageFilter = @Json.Serialize(ViewBag.CurrentLanguageFilter);
    if (languageFilter != null) {
        $(function () {
            $('#language-filter').val(languageFilter);
        });
    }
</script>

<div class="card shadow p-5">
    <h1 class="display-4" dir="rtl">
        מאגר הסרטים
        <a class="btn btn-outline-light float-left" asp-action="Create"><i class="fas fa-plus"></i></a>
        <a class="btn btn-outline-light float-left" data-toggle="modal" data-target="#filters">
            <i class="fas fa-filter"></i>
        </a>

        <!-- Modal -->
        <div class="modal fade" id="filters" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="btn btn-sm" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form asp-controller="Movies" asp-action="Index" method="get">
                            <div class="form-group row">
                                <p class="col-sm-3">שם הסרט:</p>
                                <div class="col">
                                    <input type="text" name="nameFilter" class="form-control form-control-sm" value="@(ViewBag.CurrentNameFilter as string)" />
                                </div>
                            </div>
                            <div class="form-group row">
                                <p class="col-sm-3">סוגה:</p>
                                <div class="col">
                                    <select id="genre-filter" asp-items="Html.GetEnumSelectList<Movie.MovieGenre>()" name="genreFilter" class="form-control form-control-sm">
                                        <option value="">הכל</option>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group row">
                                <p class="col-sm-3">שפה:</p>
                                <div class="col">
                                    <select id="language-filter" asp-items="@(new SelectList(ViewBag.Languages, "Value", "Text"))" name="languageFilter" class="form-control form-control-sm">
                                        <option value="">הכל</option>
                                    </select>
                                </div>
                            </div>
                            <input type="submit" value="חפש סרט" class="btn btn-danger" />
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </h1>

    <hr class="my-4">

    <div class="container">
        <div class="row row-cols-md-4">
            @foreach (var item in Model)
            {
                <div class="col mb-4">
                    <div id="card-movie" class="card h-100">
                        <img class="embed-responsive-item rounded" src="@(item.ImageUrl)" alt="movie poster">
                        <div class="card-img-overlay hoverOverlay bg-dark text-white rounded">
                            <h2 class="card-title">
                                <a asp-action="Details" asp-route-id="@item.Id" class="card-link">
                                    @Html.DisplayFor(modelItem => item.Name)
                                </a>
                            </h2>
                            <h3 class="card-subtitle text-muted">@Html.DisplayFor(modelItem => item.Genre)</h3>
                            <span class="rating"><strong>@Html.DisplayFor(modelItem => item.Rating)</strong>/10 <i class="fas fa-star rotate"></i></span>

                            @if (!String.IsNullOrEmpty(item.TrailerUrl))
                            {
                                <!-- Button trigger modal -->
                                <a class="btn btn-outline-danger rounded-circle align-middle play-button" data-toggle="modal" data-target="@("#trailer" + item.Id)">
                                    <i class="fas fa-play"></i>
                                </a>
                            }
                            <div class="movieActions mx-auto">
                                @{var isMovieAlreadyWatched = (account.MovieWatched != null) ? account.MovieWatched.FirstOrDefault(m => m.Id == item.Id) : null;}
                                @{string iconEye = (isMovieAlreadyWatched == null) ? "fa-eye" : "fa-eye-slash"; }
                                <form asp-action="@((isMovieAlreadyWatched == null)? "AddMovieWatched": "DeleteMovieWatched")" asp-route-id="@item.Id" asp-route-path="Index" method="post">
                                    <button type="submit" class="btn btn-outline-light btn-sm fa @iconEye"></button>
                                </form>
                                @{var isMovieAlreadyInWatchlist = (account.MovieWatchlist != null) ? account.MovieWatchlist.FirstOrDefault(m => m.Id == item.Id) : null;}
                                @{string iconPlus = (isMovieAlreadyInWatchlist == null) ? "fa-plus" : "fa-minus"; }
                                <form asp-action="@((isMovieAlreadyInWatchlist == null)? "AddMovieWatchlist": "DeleteMovieWatchlist")" asp-route-id="@item.Id" asp-route-path="Index" method="post">
                                    <button type="submit" class="btn btn-outline-light btn-sm fa @iconPlus"></button>
                                </form>
                            </div>
                        </div>
                    </div>

                    <!-- Modal -->
                    <div class="modal fade" id="@("trailer" + item.Id)" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content bg-dark">
                                <div class="modal-header">
                                    <button type="button" class="btn btn-outline-light" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    @if (!String.IsNullOrEmpty(item.TrailerUrl))
                                    {
                                        <iframe width="420" height="315"
                                                src="@(item.TrailerUrl.Replace("watch?v=", "embed/"))">
                                        </iframe>
                                    }
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
    <div class="pagination-container">
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page, currentNameFilter = ViewBag.CurrentNameFilter, currentGenreFilter = ViewBag.CurrentGenreFilter, currentLanguageFilter = ViewBag.CurrentLanguageFilter }))
    </div>

    @await Component.InvokeAsync("RecommendMovie")
</div>

MovieApp/Views/Movies/Seen.cshtml
@model IEnumerable<MovieApp.Models.Movie>

@{ var account = ViewData["account"] as Account;}

@if (account.MovieWatched != null && account.MovieWatched.Count > 0)
{
<div class="container">
    <div class="row">
        <div class="flex-wrap-movielist">
            @foreach (var movie in account.MovieWatched)
            {
                <div class="movie-item-style-2 movie-item-style-1">

                    <img width="170" height="200" src="@(movie.ImageUrl)" alt="@movie.Name">

                    <div class="hvr-inner">
                        <a class="btn btn-secondary btn-sm fa fa-info-circle mr-3" asp-action="Details" asp-route-id="@movie.Id"></a>
                        <a class="btn btn-secondary btn-sm fa fa-edit mr-3" asp-action="Edit" asp-route-id="@movie.Id"></a>

                        @{var isMovieAlreadyWatched = (account.MovieWatched != null) ? account.MovieWatched.FirstOrDefault(m => m.Id == movie.Id) : null;}
                        @{string icon = (isMovieAlreadyWatched == null) ? "fa-eye" : "fa-eye-slash"; }
                        <form asp-action="@((isMovieAlreadyWatched == null) ? "AddMovieWatched" : "DeleteMovieWatched")" asp-route-id="@movie.Id" asp-route-path="Seen" method="post">
                            <button id="@movie.Id-seen" type="submit" class="btn btn-secondary btn-sm fa @icon mr-3"></button>
                        </form>
         
                    </div>

                    <div class="mv-item-infor">
                        <h6><a asp-controller="Movies" asp-action="Details" asp-route-id="@movie.Id">@movie.Name</a></h6>
                        <p class="rate"><i class="fa fa-star"></i><span>@movie.Rating</span> /10</p>
                    </div>

                </div>
            }
            </div>
        </div>
    </div>
}else
{
    <br />
    <div class="jumbotron">
        <h2>אין לך עדיין סרטים שראית!</h2>

        <p>
            <div class="alert alert-secondary">
                תתחיל לראות סרטים, אל תפספס!
            </div>
        </p>
    </div>
}

MovieApp/Views/Movies/Watchlist.cshtml
@model IEnumerable<MovieApp.Models.Movie>

@{ var account = ViewData["account"] as Account;}

<div class="jumbotron">
    <h1 class="display-4" dir="rtl">רשימת צפייה:</h1>
    <hr class="my-4">

   @if (account.MovieWatchlist != null && account.MovieWatchlist.Count > 0)

    {
<div class="row row-cols-1 row-cols-md-3">

   @foreach (var movie in account.MovieWatchlist)
    {
<div class="image col mb-4">
    <div class="actions">
        @{var isMovieAlreadyInWatchlist = (account.MovieWatchlist != null) ? account.MovieWatchlist.FirstOrDefault(m => m.Id == movie.Id) : null;}
        @{string iconPlus = (isMovieAlreadyInWatchlist == null) ? "fa-plus" : "fa-minus"; }
        <form asp-action="@((isMovieAlreadyInWatchlist == null)? "AddMovieWatchlist": "DeleteMovieWatchlist")" asp-route-id="@movie.Id" asp-route-path="Watchlist" method="post">
            <button type="submit" class="btn btn-light pull-right">

                <span><i class="fa @iconPlus"></i></span>
            </button>        
        </form>
        

    </div>
    <a asp-action="Details" asp-route-id="@movie.Id">
        <div class="hover hover-5 text-white rounded">
            <img src="@(movie.ImageUrl)" alt="@movie.Name">
            <div class="hover-overlay"></div>
            <div class="hover-5-content">
                <h3 class="hover-5-title text-uppercase font-weight-light mb-0">
                    <strong class="font-weight-bold text-white">@movie.Name </strong>
                    <span><strong>@movie.Rating</strong>/10 <i class="fas fa-star"></i></span><p />
                </h3>

            </div>
        </div>
    </a>
</div>}
</div> }
            else
            {
<p dir="rtl">אין סרטים ברשימת צפייה...</p>
@await Component.InvokeAsync("RecommendMovie", "Watchlist") 

}
</div>

<style>

    .image {
        position: relative;
    }

        .image .actions {
            z-index: 100;
            display: block;
            position: absolute;
        }

            .image .actions form {
                display: inline-block;
            }

    .hover {
        overflow: hidden;
        position: relative;
        padding-bottom: 60%;
    }

    .hover-overlay {
        width: 100%;
        height: 100%;
        position: absolute;
        top: 0;
        left: 0;
        z-index: 90;
        transition: all 0.4s;
    }

    .hover img {
        width: 100%;
        position: absolute;
        top: 0;
        left: 0;
        transition: all 0.3s;
    }

    .hover-content {
        position: relative;
        z-index: 99;
    }

    .hover-5::after {
        content: '';
        width: 100%;
        height: 10px;
        background: #f5365c;
        position: absolute;
        bottom: -10px;
        left: 0;
        display: block;
        transition: all 0.3s;
        z-index: 999;
    }

    .hover-5 .hover-overlay {
        background: rgba(0, 0, 0, 0.4);
    }

    .hover-5-title {
        position: absolute;
        bottom: 1rem;
        left: 0;
        transition: all 0.3s;
        padding: 2rem 3rem;
        z-index: 99;
    }

        .hover-5-title span {
            transition: all 0.4s;
            opacity: 0;
            color: #f5365c;
        }

    .hover-5:hover .hover-overlay {
        background: rgba(0, 0, 0, 0.8);
    }

    .hover-5:hover .hover-5-title {
        bottom: 0;
    }

        .hover-5:hover .hover-5-title span {
            opacity: 1;
        }

    .hover-5:hover::after {
        bottom: 0;
    }
</style>