MovieApp/Models/Soundtrack.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MovieApp.Models
{
    public class Soundtrack
    {
        public int Id { get; set; }

        [Display(Name = "שם")]
        public string Name { get; set; }

        [Display(Name = "משך בדקות")]
        public double Duration { get; set; }

        [Display(Name = "כתובת לפסקול")]
        public string SoundtrackUrl { get; set; }

        [Display(Name = "סרטים בהם מנוגן")]
        public ICollection<SoundtrackOfMovie> SoundtrackOfMovies { get; set; }

        [Display(Name = "כותב")]
        public Official Writer { get; set; }

        [Display(Name = "מבצע")]
        public Official Performer { get; set; }

        public enum SoundtrackAverageOfOptions
        {
            [Display(Name = "משך בדקות")]
            Duration
        }
    }
}

MovieApp/Controllers/SoundtracksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MovieApp.Data;
using MovieApp.Models;
using X.PagedList;

namespace MovieApp.Controllers
{
    [Authorize]
    public class SoundtracksController : Controller
    {
        private readonly MovieAppContext _context;

        public SoundtracksController(MovieAppContext context)
        {
            _context = context;
        }

        // GET: Soundtracks
        public async Task<IActionResult> Index(string nameFilter, string currentNameFilter, int? page)
        {
            var soundtracks = await _context.Soundtrack
                .Include(s => s.Writer)
                .Include(s => s.Performer)
                .ToListAsync();

            if (nameFilter != null)
            {
                page = 1;
            }
            else
            {
                nameFilter = currentNameFilter;
            }

            ViewBag.CurrentNameFilter = nameFilter;

            if (!String.IsNullOrEmpty(nameFilter))
            {
                soundtracks = soundtracks.Where(s => s.Name.ToLower().Contains(nameFilter.ToLower())).ToList();
            }

            int pageSize = 25;
            int pageNumber = page ?? 1;

            return View(soundtracks.ToPagedList(pageNumber, pageSize));
        }

        // GET: Soundtracks/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var soundtrack = await _context.Soundtrack
                .Include(s => s.SoundtrackOfMovies).ThenInclude(sof => sof.Movie)
                .Include(s => s.Writer)
                .Include(s => s.Performer)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (soundtrack == null)
            {
                return NotFound();
            }

            return View(soundtrack);
        }


        // GET: Soundtracks/Create
        public IActionResult Create()
        {
            ViewBag.WriterId = new SelectList(_context.Official, "Id", "Id");
            ViewBag.PerformerId = new SelectList(_context.Official, "Id", "Id");
            IEnumerable<SelectListItem> officialNameSelectList = from o in _context.Official
                                                                 select new SelectListItem
                                                                 {
                                                                     Value = o.Id.ToString(),
                                                                     Text = o.FirstName + " " + o.LastName
                                                                 };
            ViewBag.WriterName = officialNameSelectList;
            ViewBag.PerformerName = officialNameSelectList;
            ViewBag.MovieId = new SelectList(_context.Movie, "Id", "Id");
            ViewBag.MovieName = new SelectList(_context.Movie, "Id", "Name");
            return View();
        }

        // POST: Soundtracks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Duration,SoundtrackUrl")] Soundtrack soundtrack, int WriterId, int PerformerId, int[] MovieId)
        {
            if (ModelState.IsValid)
            {
                soundtrack.Writer = _context.Official.FirstOrDefault(o => o.Id == WriterId);
                soundtrack.Performer = _context.Official.FirstOrDefault(o => o.Id == PerformerId);
                soundtrack.SoundtrackOfMovies = new List<SoundtrackOfMovie>();
                foreach (var id in MovieId)
                {
                    soundtrack.SoundtrackOfMovies.Add(new SoundtrackOfMovie() { MovieId = id, SoundtrackId = soundtrack.Id });
                }

                _context.Add(soundtrack);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(soundtrack);
        }

        // GET: Soundtracks/Edit/5

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var soundtrack = await _context.Soundtrack
                .Include(s => s.Writer)
                .Include(s => s.Performer)
                .Include(s => s.SoundtrackOfMovies).ThenInclude(som => som.Movie)
                .FirstOrDefaultAsync(o => o.Id == id);
            if (soundtrack == null)
            {
                return NotFound();
            }

            IEnumerable<SelectListItem> writerNameSelectList = from o in _context.Official
                                                                 select new SelectListItem
                                                                 {
                                                                     Value = o.Id.ToString(),
                                                                     Text = o.FirstName + " " + o.LastName,
                                                                     Selected = o.Id == soundtrack.Writer.Id
                                                                 };
            IEnumerable<SelectListItem> performerNameSelectList = from o in _context.Official
                                                               select new SelectListItem
                                                               {
                                                                   Value = o.Id.ToString(),
                                                                   Text = o.FirstName + " " + o.LastName,
                                                                   Selected = o.Id == soundtrack.Performer.Id
                                                               };
            ViewBag.WriterName = writerNameSelectList;
            ViewBag.PerformerName = performerNameSelectList;

            List<SelectListItem> movieNameSelectList = new List<SelectListItem>();
            foreach (var m in _context.Movie)
            {
                SelectListItem s = new SelectListItem();
                s.Value = m.Id.ToString();
                s.Text = m.Name;
                s.Selected = soundtrack.SoundtrackOfMovies.Any(som => m.Id == som.MovieId);
                movieNameSelectList.Add(s);
            }

            ViewBag.MovieName = movieNameSelectList;
            
            return View(soundtrack);
        }

        // POST: Soundtracks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Duration,SoundtrackUrl")] Soundtrack soundtrack, int WriterId, int PerformerId, int[] MovieId)
        {
            if (id != soundtrack.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    soundtrack.Writer = _context.Official.First(o => o.Id == WriterId);
                    soundtrack.Performer = _context.Official.First(o => o.Id == PerformerId);
                    soundtrack.SoundtrackOfMovies = new List<SoundtrackOfMovie>();
                    foreach (var movieId in MovieId)
                    {
                        soundtrack.SoundtrackOfMovies.Add(new SoundtrackOfMovie() { MovieId = movieId, SoundtrackId = soundtrack.Id });
                    }

                    _context.SoundtrackOfMovie.RemoveRange(_context.SoundtrackOfMovie.Where(som => som.SoundtrackId == soundtrack.Id));
                    _context.SoundtrackOfMovie.AddRange(soundtrack.SoundtrackOfMovies);

                    _context.Update(soundtrack);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SoundtrackExists(soundtrack.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(soundtrack);
        }

        // GET: Soundtracks/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var soundtrack = await _context.Soundtrack
                .FirstOrDefaultAsync(m => m.Id == id);
            if (soundtrack == null)
            {
                return NotFound();
            }

            return View(soundtrack);
        }

        // POST: Soundtracks/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var soundtrack = await _context.Soundtrack.FindAsync(id);
            _context.Soundtrack.Remove(soundtrack);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SoundtrackExists(int id)
        {
            return _context.Soundtrack.Any(e => e.Id == id);
        }
    }
}

MovieApp/Views/Soundtracks/Create.cshtml
@model MovieApp.Models.Soundtrack

@{
    ViewData["Title"] = "יצירה";
}

<div class="row">
    <div class="col-xl-8 order-xl-1">
        <div class="card bg-secondary shadow">
            <div class="card-header bg-white border-0">
                <div class="row align-items-center">
                    <div class="col-8">
                        <h3 class="mb-0">יצירת פסקול</h3>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <form asp-action="Create">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="Name" class="control-label"></label>
                                <input asp-for="Name" class="form-control" />
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="Duration" class="control-label"></label>
                                <input asp-for="Duration" class="form-control" />
                                <span asp-validation-for="Duration" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="SoundtrackUrl" class="control-label"></label>
                                <input asp-for="SoundtrackUrl" class="form-control" />
                                <span asp-validation-for="SoundtrackUrl" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="SoundtrackOfMovies" class="control-label"></label>
                                <select name="MovieId" class="form-control" asp-items="ViewBag.MovieName" multiple></select>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="Writer" class="control-label"></label>
                                <select name="WriterId" class="form-control" asp-items="ViewBag.WriterName"></select>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="Performer" class="control-label"></label>
                                <select name="PerformerId" class="form-control" asp-items="ViewBag.PerformerName"></select>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <input type="submit" value="יצירה" class="btn btn-primary" />
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<div>
    <a asp-action="Index">בחזרה לרשימה</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MovieApp/Views/Soundtracks/Details.cshtml
@model MovieApp.Models.Soundtrack

@{
    ViewData["Title"] = "פרטי פסקול";
}


<div class="row" style="margin-bottom: 50px">
    <div class="col-xl-8 order-xl-1">
        <div class="card bg-secondary shadow">
            <div class="card-header">
                <h3 class="mb-0"> @Html.DisplayFor(model => model.Name)</h3>
            </div>
            <div class="card-body">
                <dl class="row">
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Duration)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Duration)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Writer)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Writer.FirstName)
                        @Html.DisplayFor(model => model.Writer.LastName)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Performer)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Performer.FirstName)
                        @Html.DisplayFor(model => model.Performer.LastName)
                    </dd>
                    <dt class="col-sm-3">
                        @Html.DisplayNameFor(model => model.SoundtrackOfMovies)
                    </dt>
                    <dd class="col-sm-10">
                        <table class="table table-bordered table-condensed table-striped table-hover"as>
                            <thead>
                                <tr>
                                    <th>
                                        @Html.DisplayNameFor(model => model.SoundtrackOfMovies.First().Movie.Name)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.SoundtrackOfMovies.First().Movie.Genre)
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.SoundtrackOfMovies)
                                {
                                    <tr onclick="window.location='/Movies/Details/@item.MovieId'" style="cursor:pointer">
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Movie.Name)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Movie.Genre)
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </dd>
                </dl>
            </div>
            <div class="card-footer">
                <a asp-action="Index" class="btn btn-primary"><i class="fa fa-arrow-right"></i> בחזרה לרשימה</a>
                <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary"><i class="fa fa-edit"></i> ערוך</a>

                @if (User.HasClaim(ClaimTypes.Role, Account.UserType.Admin.ToString()))
                {
                    <form asp-action="Delete" style="display: inline-block;">
                        <input type="hidden" asp-for="Id" />
                        <input type="submit" value="מחק" class="btn btn-primary" />
                    </form>
                }
            </div>
        </div>
    </div>
</div>

MovieApp/Views/Soundtracks/Edit.cshtml
@model MovieApp.Models.Soundtrack

@{
    ViewData["Title"] = "Edit";
}

<div class="row">
    <div class="col-xl-8 order-xl-1">
        <div class="card bg-secondary shadow">
            <div class="card-header bg-white border-0">
                <div class="row align-items-center">
                    <div class="col-8">
                        <h3 class="mb-0">עריכת פסקול</h3>
                    </div>
                </div>
            </div>
            <form asp-action="Edit">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <input type="hidden" asp-for="Id" />
                            <div class="form-group">
                                <label asp-for="Name" class="control-label"></label>
                                <input asp-for="Name" class="form-control" />
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="Duration" class="control-label"></label>
                                <input asp-for="Duration" class="form-control" />
                                <span asp-validation-for="Duration" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="SoundtrackUrl" class="control-label"></label>
                                <input asp-for="SoundtrackUrl" class="form-control" />
                                <span asp-validation-for="SoundtrackUrl" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="SoundtrackOfMovies" class="control-label"></label>
                                <select name="MovieId" class="form-control" asp-items="ViewBag.MovieName" multiple></select>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="Writer" class="control-label"></label>
                                <select name="WriterId" class="form-control" asp-items="ViewBag.WriterName"></select>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="Performer" class="control-label"></label>
                                <select name="PerformerId" class="form-control" asp-items="ViewBag.PerformerName"></select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <div class="form-group">
                        <a asp-action="Index" class="btn btn-primary">בחזרה לרשימה</a>
                        <input type="submit" value="שמירה" class="btn btn-primary" />
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MovieApp/Views/Soundtracks/Index.cshtml
@using X.PagedList.Mvc.Core;
@model X.PagedList.IPagedList<MovieApp.Models.Soundtrack>

@{
    ViewData["Title"] = "מאגר הפסקולים";
}
<!-- CSS -->
<link type="text/css" href="~/css/soundtracksIndex.css" rel="stylesheet" asp-append-version="true">


<div class="jumbotron">
    <h1 class="display-4" dir="rtl">
        מאגר הפסקולים
        <a class="btn btn-outline-light float-left" asp-action="Create"><i class="fas fa-plus"></i></a>
        <a class="btn btn-outline-light float-left" data-toggle="modal" data-target="#filters">
            <i class="fas fa-filter"></i>
        </a>

        <!-- Modal -->
        <div class="modal fade" id="filters" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="btn btn-sm" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form asp-controller="Soundtracks" asp-action="Index" method="get">
                            <div class="form-group row">
                                <p class="col-sm-3">שם:</p>
                                <div class="col">
                                    <input type="text" name="nameFilter" class="form-control form-control-sm" value="@(ViewBag.CurrentNameFilter as string)" />
                                </div>
                            </div>

                            <input type="submit" value="חפש" class="btn btn-danger" />
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </h1>
</div>

<div class="card shadow">
    <div class="table-responsive">
        <table class="table align-items-center table-flush">
            <thead class="thead-light">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.FirstOrDefault().Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.FirstOrDefault().Duration)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.FirstOrDefault().Writer)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.FirstOrDefault().Performer)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Duration)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Writer.FirstName)
                            @Html.DisplayFor(modelItem => item.Writer.LastName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Performer.FirstName)
                            @Html.DisplayFor(modelItem => item.Performer.LastName)
                        </td>
                        <td>
                            <a class="btn btn-outline-primary btn-sm fa fa-info-circle mr-3" asp-action="Details" asp-route-id="@item.Id"></a>
                            <a class="btn btn-outline-primary btn-sm fa fa-edit mr-3" asp-action="Edit" asp-route-id="@item.Id"></a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="pagination-container">
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page, currentNameFilter = ViewBag.CurrentNameFilter }))
    </div>
</div>


<p>
    <a class="btn btn-primary" asp-action="Create">צור חדש</a>
</p>